# Generated by Django 6.0.6 on 2026-06-13 08:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name_id', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('factor', models.DecimalField(decimal_places=3, max_digits=4)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GlassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name_id', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name_id', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('kg_per_m', models.DecimalField(decimal_places=3, max_digits=6)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('basis', models.CharField(choices=[('kg', 'Per kilogram'), ('unit', 'Per unit')], max_length=8)),
                ('color_primary', models.CharField(default='#327EBC', max_length=9)),
                ('color_secondary', models.CharField(default='#100E2B', max_length=9)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name_id', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('kg_per_m', models.DecimalField(decimal_places=3, max_digits=6)),
                ('glass_factor', models.DecimalField(decimal_places=3, max_digits=4)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_per_opening', models.DecimalField(decimal_places=2, default=Decimal('350000'), max_digits=12)),
                ('logistics_flat', models.DecimalField(decimal_places=2, default=Decimal('750000'), max_digits=12)),
                ('install_per_day', models.DecimalField(decimal_places=2, default=Decimal('1200000'), max_digits=12)),
                ('units_per_install_day', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service rates',
                'verbose_name_plural': 'Service rates',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16)),
                ('effective_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('rate_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='cpq.partner')),
            ],
            options={
                'ordering': ['partner', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='cpq.kitcomponent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_links', to='cpq.product')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='kit',
            field=models.ManyToManyField(related_name='products', through='cpq.ProductKit', to='cpq.kitcomponent'),
        ),
        migrations.CreateModel(
            name='ProductUnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='cpq.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_prices', to='cpq.product')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=24)),
                ('client_name', models.CharField(max_length=200)),
                ('client_contact', models.CharField(blank=True, max_length=200)),
                ('client_site', models.CharField(blank=True, max_length=300)),
                ('project_type', models.CharField(default='0', max_length=8)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=5)),
                ('template_id', models.CharField(default='pdf', max_length=16)),
                ('materials', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('small_parts', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('assembly', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('logistics', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('installation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('install_days', models.PositiveIntegerField(default=0)),
                ('cost_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cpq.partner')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cpq.pricelist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_id', models.CharField(max_length=120)),
                ('product_name_en', models.CharField(max_length=120)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('per_unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('small_parts_per_unit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('parts', models.JSONField(default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cpq.finish')),
                ('glass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cpq.glasstype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cpq.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cpq.quote')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('partner', 'version'), name='unique_partner_version'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('partner',), name='one_current_pricelist_per_partner'),
        ),
        migrations.AddConstraint(
            model_name='productkit',
            constraint=models.UniqueConstraint(fields=('product', 'component'), name='unique_product_component'),
        ),
        migrations.AddConstraint(
            model_name='productunitprice',
            constraint=models.UniqueConstraint(fields=('price_list', 'product'), name='unique_pricelist_product'),
        ),
    ]
